//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COCAAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://thulium.smcdacon.com:7077/BC130_POWER_TEST/WS/Sem%20Calaca%20Power%20Corpo" +
            "ration/Codeunit/GetPRDetailsCOCA")]
        public string COCAAPI_GetPRDetailsFromNAV_GetPRDetailsCOCA {
            get {
                return ((string)(this["COCAAPI_GetPRDetailsFromNAV_GetPRDetailsCOCA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://thulium.smcdacon.com:7077/BC130_POWER_TEST/WS/Southwest%20Luzon%20Power%20" +
            "Gen%20Corp/Codeunit/GetPODetailsCOCA")]
        public string COCAAPI_GetPODetailsFromNAV_GetPODetailsCOCA {
            get {
                return ((string)(this["COCAAPI_GetPODetailsFromNAV_GetPODetailsCOCA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://thulium.smcdacon.com:7077/BC130_POWER_TEST/WS/Sem%20Calaca%20Power%20Corpo" +
            "ration/Codeunit/GetPIDetailsCOCA")]
        public string COCAAPI_GetPIDetailsFromNAV_GetPIDetailsCOCA {
            get {
                return ((string)(this["COCAAPI_GetPIDetailsFromNAV_GetPIDetailsCOCA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vela.semcalaca.com:7077/BC2019_CPC/WS/Sem%20Calaca%20Power%20Corporation/C" +
            "odeunit/CocaHandshake")]
        public string COCAAPI_CocaHandshake_CocaHandshake {
            get {
                return ((string)(this["COCAAPI_CocaHandshake_CocaHandshake"]));
            }
        }
    }
}
