//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace COCAAPI.GetPIDetailsFromNAV {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetPIDetailsCOCA_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/GetPIDetailsCOCA")]
    public partial class GetPIDetailsCOCA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPIForCOCAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetPIDetailsCOCA() {
            this.Url = global::COCAAPI.Properties.Settings.Default.COCAAPI_GetPIDetailsFromNAV_GetPIDetailsCOCA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPIForCOCACompletedEventHandler GetPIForCOCACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/GetPIDetailsCOCA:GetPIForCOCA", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/GetPIDetailsCOCA", ResponseElementName="GetPIForCOCA_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/GetPIDetailsCOCA", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetPIForCOCA(ref XMLPortForCOCAPIHeader xMLCOCAPIHeader) {
            object[] results = this.Invoke("GetPIForCOCA", new object[] {
                        xMLCOCAPIHeader});
            xMLCOCAPIHeader = ((XMLPortForCOCAPIHeader)(results[0]));
        }
        
        /// <remarks/>
        public void GetPIForCOCAAsync(XMLPortForCOCAPIHeader xMLCOCAPIHeader) {
            this.GetPIForCOCAAsync(xMLCOCAPIHeader, null);
        }
        
        /// <remarks/>
        public void GetPIForCOCAAsync(XMLPortForCOCAPIHeader xMLCOCAPIHeader, object userState) {
            if ((this.GetPIForCOCAOperationCompleted == null)) {
                this.GetPIForCOCAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPIForCOCAOperationCompleted);
            }
            this.InvokeAsync("GetPIForCOCA", new object[] {
                        xMLCOCAPIHeader}, this.GetPIForCOCAOperationCompleted, userState);
        }
        
        private void OnGetPIForCOCAOperationCompleted(object arg) {
            if ((this.GetPIForCOCACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPIForCOCACompleted(this, new GetPIForCOCACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50109")]
    public partial class XMLPortForCOCAPIHeader {
        
        private PIHeader[] pIHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PIHeader")]
        public PIHeader[] PIHeader {
            get {
                return this.pIHeaderField;
            }
            set {
                this.pIHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50109")]
    public partial class PIHeader {
        
        private string pPINNoField;
        
        private string invoiceDateField;
        
        private string invoiceAmountField;
        
        private string pONoField;
        
        /// <remarks/>
        public string PPINNo {
            get {
                return this.pPINNoField;
            }
            set {
                this.pPINNoField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceAmount {
            get {
                return this.invoiceAmountField;
            }
            set {
                this.invoiceAmountField = value;
            }
        }
        
        /// <remarks/>
        public string PONo {
            get {
                return this.pONoField;
            }
            set {
                this.pONoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetPIForCOCACompletedEventHandler(object sender, GetPIForCOCACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPIForCOCACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPIForCOCACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public XMLPortForCOCAPIHeader xMLCOCAPIHeader {
            get {
                this.RaiseExceptionIfNecessary();
                return ((XMLPortForCOCAPIHeader)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591